### ISSUE TITLE
Modified-Huff-Three-Step Floating Catchment Area method

### ISSUE THREAD

**Issue by tenisman12** [egrueebler/fca#8]
good morning, I am writing to report a problem with the script, when I try to calculate the spatial index I get only Nan for all the rows. I compare with the previous method, the three-step method, and it does give me a value for all rows

![fca_script_error](https://user-images.githubusercontent.com/69608535/175803706-f4ce75fa-13b2-4257-8114-53e9a965b14a.jpg)

**Comment by munterfi** [comment]
Hi @tenisman12 thanks for reporting. Can you provide a reproducible example?

**Comment by tenisman12** [comment]
i try to attach here my files, how can i do to provide you an example?

**Comment by munterfi** [comment]
Is it possible for you to post an example, which only uses a small subset of the data directly here in the comments without uploading files?

So we can investigate the problem in more detail and debug it. Maybe the [reprex](https://github.com/tidyverse/reprex) R package can help you to render the example from R to Markdown.

See the example from the README:

- Create a small example dataset:

```R
set.seed(123)

# Population df with column for size
pop <- data.frame(
  orig_id = letters[1:10],
  size = c(100, 200, 50, 100, 500, 50, 100, 100, 50, 500)
)

# Supply df with column for capacity
sup <- data.frame(
  dest_id = as.character(1:3),
  capacity = c(1000, 200, 500)
)

# Distance matrix with travel times from 0 to 30
D <- matrix(
  runif(30, min = 0, max = 30),
  ncol = 10, nrow = 3, byrow = TRUE,
  dimnames = list(c(1:3), c(letters[1:10]))
)
D
#>           a        b        c        d        e         f         g         h
#> 1  8.627326 23.64915 12.26931 26.49052 28.21402  1.366695 15.843165 26.772571
#> 2 28.705000 13.60002 20.32712 17.17900  3.08774 26.994749  7.382632  1.261786
#> 3 26.686179 20.78410 19.21520 29.82809 19.67117 21.255914 16.321981 17.824261
#>           i         j
#> 1 16.543050 13.698442
#> 2  9.837622 28.635109
#> 3  8.674792  4.413409
```

- Then Illustrate the problem:

```R
library(fca)

...

#> Here are the NaNs :-)
```
